server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fast?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
netty:
  port: 9009
  read-timeout: 15 #读超时 15分钟
  threads:
    boss: 1
    worker: 4
    business: 20 #业务线程数量
