server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.4.174.7:3306/ry?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: ENC(c3Csl1RZ0/+vEVFrO+sMsZe/xW19uawA)
netty:
  port: 8082
  read-timeout: 15
  threads:
    boss: 1
    worker: 4
    business: 20
jasypt:
  encryptor:
    password: 998877

mybatis-plus:
  mapper-locations: classpath:sql-mapper/*.xml
